### ISSUE TITLE
src folder is missing in repository

### ISSUE THREAD

**Issue by TrustedRich** [creativetimofficial/ct-vue-material-kit-pro#1]
Hi,
 It looks like the src folder with the example files did not get uploaded to the repository. Looking forward to seeing this demo of the pro ui kit!

thanks,
 - Rich

**Comment by dragosct** [comment]
Hi, @TrustedRich! Thank you for your interest in our products. Do you refer on this GitHub repo that the src folder wasn't uploaded? 

Regards, 
Dragos

**Comment by TrustedRich** [comment]
Yes..

**Comment by dragosct** [comment]
Hi! On our GitHub repos (the pro version of the product) always we don't have the entire product only like you see the issue template and the readme file. 

Regards, 
Dragos
