### ISSUE TITLE
Not working on Internet Explorer

### ISSUE THREAD

**Issue by dpedrinha** [creativetimofficial/ct-vue-material-kit-pro#10]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

On Internet Explorer the page doesn't show. Console doesn't throw any errors. Just a blank page.
You can try it here: www.tcmpoints.com

**Comment by dragosct** [comment]
Hi, @dpedrinha! Vuematerial.io framework doesn't have the support for the IE, maybe from their future updates, it will be available also for IE. Thank you for your understanding! 

Regards, 
Dragos

**Comment by dpedrinha** [comment]
Ok.

Is there a way to at least show a message to the users?

Em qua, 15 de mai de 2019 03:46, dragosct <notifications@github.com>
escreveu:

**Comment by dragosct** [comment]
Hi! Please read the readme.md from the main page here on GitHub, there you will see which browsers support the product. 

Regards,
Dragos
