### ISSUE TITLE
dropdown list behind modal

### ISSUE THREAD

**Issue by aim-bying** [creativetimofficial/ct-vue-material-kit-pro#11]
Hi,

I use a dropdown list on modal form. But it appears behind modal form.
I have to add z-index: 9999 !important; in .md-menu-content to workaround it. Is there any better way to make it work? Is this a bug?

**Comment by dragosct** [comment]
Hi, @aimroboticsbying! Thank you for using our products. This workaround's good, it will not have a negative effect, so you can use it. 

Regards, 
Dragos
