### ISSUE TITLE
how to import into node_modules / use components from library

### ISSUE THREAD

**Issue by addijhaq** [creativetimofficial/ct-vue-material-kit-pro#12]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

With other ui libraries i do an `npm -i <ui-library-name>` is there a way to make your components into a npm package? Is there any way to put the source code in node_modules and reference single components with import statements? 

If not, I'm finding your kit very difficult to work with. This was not explained (that this is a boilerplate template, not a component framework like bootstrap-vue, veutify, etc) up-front in the description with purchase.

**Comment by dragosct** [comment]
Hi, @addijhaq! Thank you for using our products. Unfortunately, our components are not ready to use by default to install them with npm, only if you put them manually on npm. This feature is in our plan in the next period to have our components ready to use with npm. 

Thank you for your understanding! 

Regards, 
Dragos
