### ISSUE TITLE
Template for a new nuxt.js project?

### ISSUE THREAD

**Issue by sparkyspider** [creativetimofficial/ct-vue-material-kit-pro#13]
Hi there,

I've just bought vue-material-kit-pro. I'd like to use it with Nuxt.js.

Do you have a template or example?

Thanks,

**Comment by fidoogle** [comment]
That is exactly my pre-purchase question. Can this UI Kit work with Nuxt? I can also do React so a similar question would be: can the react version of UI Kit work with NextJS?

**Comment by fidoogle** [comment]
After signing up for an account, I found a Nuxt version here: https://www.creative-tim.com/product/nuxt-now-ui-kit-pro

Sorry, I think it is not the same template and it might now even be the real NuxtJS we know.

**Comment by dragosct** [comment]
Hi! Thank you for using our products. Here below we have all the nuxt and next products available right now. 
https://www.creative-tim.com/templates/nuxtjs 
https://www.creative-tim.com/templates/nextjs

Regards,
Dragos
