### ISSUE TITLE
Applying Creative Tim CSS to Vue Material

### ISSUE THREAD

**Issue by sparkyspider** [creativetimofficial/ct-vue-material-kit-pro#14]
Hi there,

Is there a way that I can npm install vue-material and then just use the CSS from the package I downloaded from Creative Tim?

Where would I find the CSS that overrides the default Vue Material?

Am I understanding this correctly.

PS: I don't like the idea of having to copy all the dependencies from the example vue-cli project I bought into my nuxt project. Maybe just the CSS.

Thanks,

**Comment by dragosct** [comment]
Hi, @sparkyspider! I will close this issue because we switched at your request this product with another. 

Regards,
Dragos

**Comment by sparkyspider** [comment]
Amazing, Thank you so much!

Sent from Mark's mobile device

Mark van Wyk
FlyH2 Aerospace
082 831 9227
