### ISSUE TITLE
[Bug] Examples - About Us Drop Down Doesn't Close in Chrome or Firefox on iPhone

### ISSUE THREAD

**Issue by ActionsMatter** [creativetimofficial/ct-vue-material-kit-pro#16]
### Version
v1.2.2
### Reproduction link
https://demos.creative-tim.com/vue-material-kit-pro/#/
### Operating System
iOS
### Device
Apple iPhone
### Browser & Version
Firefox and Chrome
### Steps to reproduce
1. Browse to above link
2. Click on 3 bars in upper right
3. Select Examples then About Us

### What is expected?
We browse to About Us Page and the drop down closes.
### What is actually happening?
We browse to About Us Page but the drop down stays open.

---
### Additional comments
This is also happening when I run Vue Material Kit Pro on my pc and browse to http://10.0.0.201:8082/ from my phone. This same behavior happens when I use firefox and go into inspect mode and toggle the device toolbar.

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product and change the entire structure based on the latest standards, please take a look to the latest version and let us know if there is still any issue.

**All the best,**
**Sajad**
