### ISSUE TITLE
[Bug] About Us - "Let's Talk" Button Zooms Page on Keyboard Input but Doesn't "Unzoom" when click on Done for entry.

### ISSUE THREAD

**Issue by ActionsMatter** [creativetimofficial/ct-vue-material-kit-pro#17]
### Version
v1.2.2
### Reproduction link
https://demos.creative-tim.com/vue-material-kit-pro/#/
### Operating System
iOS
### Device
iPhone
### Browser & Version
Chrome and Firefox
### Steps to reproduce
1. Browse to link above
2. Select 3 bars in upper right
3. Chose Examples - About Us (then close menu )
4. Scroll to Bottom and click on "Your Name"
4b. Notice that the page zooms in some.
5. Type in something and the select Done
### What is expected?
Expected that once we click Done the page returns to normal zoom level.
### What is actually happening?
When we hit done, the page does not return to normal zoom level. We need to pinch the screen to get the website to go to normal zoom mode.

---
### Additional comments
This is also happening on the web page I created using Vue Material Kit. I was able to reproduce it online.

**Comment by sajadevo** [comment]
**Hi there**

We've just updated the product and change the entire structure based on the latest standards, please take a look to the latest version and let us know if there is still any issue.

**All the best,**
**Sajad**
