### ISSUE TITLE
Having problems installing the template with npm into my application

### ISSUE THREAD

**Issue by jrisaza** [creativetimofficial/ct-vue-material-kit-pro#2]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
I was expecting to be able to install the template via npm into my project.

# Current Behavior
npm install the template from a file, but it is not working  

I am having trouble setting up the template in my Vue app.  I installed it via npm into my Vue app, but I cannot find a way to make it work.  After the installation, the build process showed me a depedency error because vue-material was not installed.  I installed it and the vue-material started working partially, I could not make it work completely.  For example, the buttons did not show the background colore correctly.  However, there is no sign of having the Pro version active.  Only the Vue Material one.

The documentation is not clear enough for me to understand what is missing.  I really need help with this.  Thanks

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. vue create myapp
2. npm install localfolder-containing-template -save
2. npm run serve
---- I start having dependency error at built time.  Vue-Material is missing.
4. npm install vue-material -save
5. npm run serve
---- now it compiled but not all css appear to be working.  I tested the the following:
      <md-button class="md-raised">Default</md-button>
      <md-button class="md-raised" :md-ripple="false">Ripple Off</md-button>
      <md-button class="md-raised md-primary">Primary</md-button>
      <md-button class="md-raised md-accent">Accent</md-button>
      <md-button class="md-raised" disabled>Disabled</md-button>

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: macbook pro
* Operating System: osx
* Browser and Version: chrome Version 71.0.3578.98

## Failure Logs

> napp@0.1.0 serve /Users/jrisaza/desarrollo/vuejs-projects/napp
> vue-cli-service serve

 INFO  Starting development server...
 98% af Failed to compile with 3 errors9:29:37 PM

These dependencies were not found:

* vue-material in ./src/main.js
* vue-material/dist/theme/default.css in ./src/main.js
* vue-material/dist/vue-material.min.css in ./src/main.js

To install them, you can run: npm install --save vue-material vue-material/dist/theme/default.css vue-material/dist/vue-material.min.css

--------
thanks

**Comment by dragosct** [comment]
Hi, @jrisaza! Thank you for using our products. Please tell me to understand, do you want to install the theme in your already vue app, right? if yes, could you give us your app to see what is happening because in our side everything it's working fine? 

Regards, 
Dragos

**Comment by jrisaza** [comment]
Hi @dragosct10 Thanks for the response.  I am creating an new empty vue-cli 3 app and trying to install it in it.  But I got your answer via the zendesk help desk about this same case, so I understand now that I should use the template as my base app structure instead of trying to install it on a project.  Installing it seem to be doable, but it is more complex.

For now, my remaining question is if you release a fix or an improvement, do you have a standard procedure to patch or upgrade the base structure that already contain my app modules in it? Actually, this was my original concern and the reason why I tried to install it instead of using it directly.

Thanks.

**Comment by dragosct** [comment]
Hi! Ok, now I understand. We don't have a standard procedure because it will not work in every project and I believe the best way would be to keep your styles separate from ours( scss ).
We've already started adding in our CHANGELOG what styles are being changed.
Another thing that you could do to make changes easily would be to have two private repos, one on which you are developing, and one on which you should keep our product unaltered, on every update that we make, you could copy our product and put it on top of that repo. Github will tell you all the differences that were made, and I think this is the best way.
I'll speak with the board and decide if we are going to add this in our live docs, the part with the private repo.

Regards, 
Dragos
