### ISSUE TITLE
[Bug] Bad capitailization of some files

### ISSUE THREAD

**Issue by jredrejo** [creativetimofficial/ct-vue-material-kit-pro#24]
### Version
1.3.0
### Reproduction link
.
### Operating System
Linux 
### Device
Laptop
### Browser & Version
chrome Versión 96.0.4664.45 
### Steps to reproduce
Trying to do yarn build /dev or whatever it always return:
* ./presentation/Cards.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Presentation.vue?vue&type=script&lang=js&
* ./presentation/Components.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Presentation.vue?vue&type=script&lang=js&
* ./presentation/Introduction.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Presentation.vue?vue&type=script&lang=js&
### What is expected?
a correct build of the app
### What is actually happening?
Several files under the /src/views/presentation folder  have not the right capitalization in their names:
introduction.vue should be Introduction.vue
components.vue should be Components.vue
and so on

---
### Solution
Check the right name files
### Additional comments
Test your code in a a OS sensitive to capitalization in name files. Windows ignores it, but other systems like Linux take it into account

**Comment by sajadevo** [comment]
**Hi @jredrejo**

We've just updated the product and change the entire structure based on the latest standards, please take a look to the latest version and let us know if there is still any issue.

**All the best,**
**Sajad**
