### ISSUE TITLE
several kits bough in bundle {including this one} contain deprecated code and do not install or even run out of box

### ISSUE THREAD

**Issue by rmasonh18** [creativetimofficial/ct-vue-material-kit-pro#25]
****KITS CONTAIN DEPRECATED CODE AND REQUIRE DEBUG AND UPDATES -- SHOULD NOT HAVE BEEN SOLD AS THEY DO NOT WORK AND PRODUCT IS DEFECTIVE UNLESS DEVELOPER DEBUG AND SPEND HOUR OR MORE TO REPAIR. PLEASE UPDATE YOUR CODEBASE TO WORKING CODE ONLY -- NOT DEPRECATED AND NEEDS DEVELOPER DEBUG AND REPAIR

**Comment by rmasonh18** [comment]
****KITS CONTAIN DEPRECATED CODE AND REQUIRE DEBUG AND UPDATES -- SHOULD NOT HAVE BEEN SOLD AS THEY DO NOT WORK AND PRODUCT IS DEFECTIVE UNLESS DEVELOPER DEBUG AND SPEND HOUR OR MORE TO REPAIR. PLEASE UPDATE YOUR CODEBASE TO WORKING CODE ONLY -- NOT DEPRECATED AND NEEDS DEVELOPER DEBUG AND REPAIR

**Comment by dragosct** [comment]
Hi, @rmasonh18! Thanks for using our products. The product is working properly. Run the command `npm install --legacy-peer-deps` and then `npm run dev` and the product will start the server.

Regards,
Dragos
