### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by dpedrinha** [creativetimofficial/ct-vue-material-kit-pro#3]
I'm running the default Vue project and I'm getting the following error on Chrome console:
`Failed to decode downloaded font: https://fonts.gstatic.com/stats/Material+Icons/normal/400`

All I did was unzip, npm install, npm run dev

**Comment by dragosct** [comment]
Hi, @dpedrinha! Thank you for using our products. Please try with this link: `<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">`.

Regards, 
Dragos

**Comment by dpedrinha** [comment]
It's already there. I didn't change anything.

`    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">`

**Comment by dragosct** [comment]
Hi! You can remove that link because we also add the material icons in this link `<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />.`.

Regards, 
Dragos

**Comment by dpedrinha** [comment]
Thank you.

How can I see a list of all fonts and icons available?

It seems there are no icons for Apple and Microsoft for <md-icon>. Just the
android one.

Regards,

Daniel

**Comment by dragosct** [comment]
Hi! Please see this list: https://vuematerial.io/components/icon. 

Regards,
Dragos

**Comment by dpedrinha** [comment]
Thank you.

I'm facing some problems on mobile. Can you please check my website (
https://tcmpoints.com). It's clipping the top and bottom content of the
header (on mobile). Any idea on how to fix this? Is there a container to
auto resize the content to fit?

Best regards,

Daniel

**Comment by dragosct** [comment]
Hi! Sorry for the late response. Please put `word-break: break-all;` on that tags that have the text outside of the box. 

Regards, 
Dragos

**Comment by dpedrinha** [comment]
Thank you for the response.

It's not outside of the box. It's being clipped by the parallax.

Please check the website on mobile to see it. It's "right there". (
https://tcmpoints.com)

**Comment by dragosct** [comment]
Hi! I already checked this on mobile but what I found it's just the text outside of the box, not an issue related to clipping. 

Regards,
Dragos

**Comment by dpedrinha** [comment]
Ok, then maybe you have a huge mobile screen or I'm using the wrong verb.

Here's what I'm seeing on a Galaxy S8.

The logo is round, it's clipped by the top of the screen. Also, the second
arrow is pointing to the text hidden behind the white background.

**Comment by dragosct** [comment]
Hi! Ok, now I get what you said, but have you tried to put that prop that I told you on that tags because the problem is from that tags who are out of the box? 

Regards, 
Dragos

**Comment by dpedrinha** [comment]
Hi.

I didn't because to be honest, I have no idea where to put them. The
content has no comments and no instructions on how everything is bound
together. It's said that some understanding of the tech is needed but it's
actually much more than "some". The scripts of the demo components are all
on the same place 3 pages, with no comments, making it really hard to
understand which part of the script goes with each component. But that part
I'm (very) slowly figuring out. The biggest problem is the CSS, I'm
completely lost.
In which tags should I put them? The h3? The parallax? The parallax's
children divs? Which box are you referring to?

Thanks.

Daniel

**Comment by dragosct** [comment]
Hi, @dpedrinha! Don't worry about this, we will fix it and we will help you with your problems related to the product. Please see this video to see where you must put the css to fix the problem. Please let us know if you succeed with this! 

[tcm.mov.zip](https://github.com/creativetimofficial/ct-vue-material-kit-pro/files/3062394/tcm.mov.zip)

Regards, 
Dragos

**Comment by dpedrinha** [comment]
Thank you for the help. I'll test it and let you know how it goes.

But you are seeing my i18n tags instead of the text. That's why we are
seeing different things. May I ask in which language your browser is?

**Comment by dpedrinha** [comment]
Ok. I added a rule to set the language to English if not supported. Please
let me know if the content is showing now or if you still see only the i18n
tags

**Comment by dragosct** [comment]
Hi! The content's same like yesterday. My browser's in English. 

Regards, 
Dragos

**Comment by dpedrinha** [comment]
That's weird. Which browser is it?

**Comment by dpedrinha** [comment]
This is what is supposed to show in English

Can you tell me if the console is showing any error?

**Comment by dpedrinha** [comment]
Also, regarding your product.

It would be really helpful if there was a tutorial on how to use your
styles. How to take a component or an example page off of the demo and
tweak it to use on my own project. Let's say, how to create my own
"body-class", change the background effect and so on. I noticed different
background effects and body-class on the examples, but I don't know where
to find the available options. What I'm finding most difficult is to find
where everything is. For instance, on the landing page, the background is
set on the script, but I have no idea where and when it is actually being
added. I found that it's being set on the basicMixins file as HeaderImage
but that's as far as I could go, I have no idea of the logic behind it. I
still don't know where and how it's being added to the pages. I noticed the
background image disappears if I remove the parallax. But what if I want a
background image with no parallax? I don't know how to change it using your
logic because I don't know where it's setting the background image to the
parallax component. You know what I mean?

The modules and components logic is fine. I can track everything through
the file names. But the global styles/mixins are really slowing down my
development.

Regards,

Daniel

**Comment by dragosct** [comment]
Hi! The console's not showing any error. Did you read the [docs](https://demos.creative-tim.com/vue-material-kit-pro/documentation/component-docs/parallax.html) about the parallax issue that you have? That global mixins are used because we don't want te repeate the same code in every page and for this we used mixins. Until now nobody tell us something like this, on the contrary some clients told us that this it's a good way to do things, but anyway this method it's not invented by us, it's an vuejs official method (please see: https://vuejs.org/v2/guide/mixins.html) and it will help you if you will understand it. Regard to the scss you can put any class that you want and style like you want, and also you can use our classes of course. We will make also tutorials in the near future. 

Regards, 
Dragos

**Comment by dpedrinha** [comment]
Yes I understand the concept of mixins. And it's great to make things
easier, specially for you on your demo or on my project. But, in my
opinion, since your product is based on components and examples, I believe
everything should be modular and not bound together by the mixins, you know
what I mean? In a way that I can pick a component or example and tweek it
right away. The way it is, I need to keep looking into the files to find
out where things are since they are all bound to project mixins, files and
variables.
And yes, your other clients may be a lot more experienced than me, all I'm
saying is that I'm having trouble with it and how I believe it would make
things easier.
Of course, with time I'm getting the hang of it and "figuring out" the
logic but would be a lot easier and faster if things were as modular as
possible.

Daniel

**Comment by dragosct** [comment]
Hi, @dpedrinha! Ok, now I understand what you said and we thank you for this feedback and we will take this into consideration. 

Regards, 
Dragos
