### ISSUE TITLE
Menu does not close on mobile

### ISSUE THREAD

**Issue by gaspo53** [creativetimofficial/ct-vue-material-kit-pro#4]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The expected behavior is the same as browsing from desktop: click on a menu item, and it will automatically collapse after target is loaded

# Current Behavior

Menu stays open even after target page has loaded

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open https://demos.creative-tim.com/vue-material-kit-pro/?_ga=2.110734983.30255889.1554120104-1780603151.1553967052#/
2. Click Menu/Sections/Teams
3. Teams page will be shown but menu will still open

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: iPhone X/8/7
* Operating System: iOS
* Browser and Version: Safari/Chrome latest

**Comment by dragosct** [comment]
Hi, @gaspo53! Thank you for using our products. This is not a bug, it was built like this intentionally. You can go to the `src/layout/MainNavbar.vue` and search for these lines of code and add what is highlighted in the image below. 

<img width="778" alt="Screenshot 2019-04-03 at 11 40 03" src="https://user-images.githubusercontent.com/17456857/55465441-d0d5ab80-5605-11e9-89d8-aa80859c495b.png">


Regards, 
Dragos

**Comment by gaspo53** [comment]
@dragosct10 thanks! Issue solved. One more thing, how can I use (in a fancy and reutilizable way) a notification? I want to show an alert if signup was successful.

Thanks

**Comment by dragosct** [comment]
Hi, @gaspo53! I'm glad that it's now fixed. You can use our notifications through a plugin for notifying alerts and you can set the container to be exactly our alerts. 

Regards, 
Dragos

**Comment by gaspo53** [comment]
Hi @dragosct10 still having the same issue with UI kit Pro.

**Comment by dragosct** [comment]
Hi! You said everything it's ok and we also tested our workaround and everything seems to be ok. What it's happening now? 

Regards, 
Dragos

**Comment by gaspo53** [comment]
@dragosct10 hi! The problem is after the navbar has been hidden. Whenever I click in the body, it re-appears. If you want, I can give you the app url and the credentials to test it, but my code is this:

`<router-link
                                v-on:click.native="$emit('menu_item_clicked');"
                                v-if="li.path"
                                :to="{
                                  path: li.path
                                }"
                              >
                                <i class="material-icons">{{ li.icon }}</i>
                                {{ $t(li.titleKey) }}
                              </router-link>`

And the handler:

`  created() {
    this.$on('menu_item_clicked', () => {
      this.NavbarStore.showNavbar = false;
      this.toggledClass = false;
  })`

When you click an option, the navbar hides. But when you click anywhere in the body, it re-appears.

**Comment by gaspo53** [comment]
@dragosct10 removing bodyClick() function seems to be the solution, but I don't know if that was created by some other reason.

**Comment by dragosct** [comment]
Hi! Now I understand. You can remove the bodyClick() function and everything will be ok. 

Regards, 
Dragos

**Comment by gaspo53** [comment]
Thanks!
