### ISSUE TITLE
[CSS Bug] - Login page layout issues on Firefox

### ISSUE THREAD

**Issue by gaspo53** [creativetimofficial/ct-vue-material-kit-pro#5]
On firefox: https://demos.creative-tim.com/vue-material-kit-pro/#/login-page

![image](https://user-images.githubusercontent.com/2250227/56819275-c59a2800-681f-11e9-94df-9a6a4d931c88.png)
 

On chrome it looks fine:

![image](https://user-images.githubusercontent.com/2250227/56819310-d3e84400-681f-11e9-8f76-8ab02224ce73.png)

**Comment by dragosct** [comment]
Hi, @gaspo53! Sorry for the late response. You can put `min-height: 100vh` to the page-header div from the below image: 

<img width="303" alt="Screenshot 2019-04-30 at 12 33 05" src="https://user-images.githubusercontent.com/17456857/56953031-4a4cb500-6b44-11e9-9356-bd8ef5d5523a.png">

Regards, 
Dragos
