### ISSUE TITLE
Modal Appearing Under Parent Elements

### ISSUE THREAD

**Issue by miketierce** [creativetimofficial/ct-vue-material-kit-pro#6]
# Expected Behavior

When opening a modal from within tab content it should appear on top of the rest of the tab content. 

# Current Behavior

https://share.vidyard.com/watch/Y8juifVN2TBNEfxHUjnbWw?

Modal is created but the Tab Icons and other div elements from within the tab content are appearing "on top" of the modal

## Context
Standard NodeJS development environment. I haven't added any additional CSS to the project that I feel could be interfering (I know you will probably shake your head reading that though lol) The modal works correctly and does not interfere with any other page elements if I take it out of the tab content section. 

* Device: Mobile & Desktop
* Operating System: Ubuntu
* Browser and Version: Chrome Version 73.0.3683.75 (Official Build) (64-bit)

**Comment by dragosct** [comment]
Hi, @miketierce! Thank you for using our products. Please, try to put on the modal-container div `position: relative;` with `z-index: 9999;`. Regards, Dragos
