### ISSUE TITLE
Signup input v-model binding

### ISSUE THREAD

**Issue by aim-bying** [creativetimofficial/ct-vue-material-kit-pro#7]
Hi,

In Signup.vue, you bind the input to array nameAttr, but the value isn't updated.
Can you please show me how to use the binding properly to get the value?

Thanks,
Ben

**Comment by dragosct** [comment]
Hi, @aimroboticsbying! Thank you for using our products. To bind the input you must put on the v-model `:value="item.nameAttr"`. 

Regards,
Dragos
