### ISSUE TITLE
Rotating Card on Microsoft Edge 

### ISSUE THREAD

**Issue by dpedrinha** [creativetimofficial/ct-vue-material-kit-pro#8]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Rotating cards shouldn't show the action button before "mouse over" and shouldn't be grey.

# Current Behavior

Rotating cards have two sides, front and back. Back is shown when "mouse over". Currently, the first time I open the page the cards are grey. If I "mouse over" they show the back, but when I move the mouse away, it still shows the action button from the back side, with the text in backwards. AFAIK this only happens on Microsoft Edge.
You can test it here: www.tcmpoints.com

Links to screenshots on OneDrive:
https://1drv.ms/u/s!AnlvHDhqbdln1BbhWo4lZz573GJN
https://1drv.ms/u/s!AnlvHDhqbdln1BVxaiObkTnghObs

**Comment by dragosct** [comment]
Hi! I just tested on Microsoft edge and everything seems to be ok with that rotating cards. 

Regards, 
Dragos

**Comment by dpedrinha** [comment]
You've accessed my website previously. Try clearing the cache and make sure your Windows is up-to-date. I just made all that and the first time the website opens, they are grey. The next times they are not grey but they show the orange buttons on the front and its label is written backwards. They should only show once the card is flipped.
I tried on a non up-to-date windows computer and the page was working fine. Once I updated it, the problem appeared. So it's clearly a problem with the latest version and the only way to update Edge, is updating Windows 10.

**Comment by dragosct** [comment]
Hi! I've used your link on my MacBook laptop, so when I tried on the windows computer everything was ok, but our windows laptop it's not updated to the latest version, so we have to update the laptop to the latest windows and then to try again to see if are some problems with those cards. Meanwhile, you can try to see if in the CSS the code for cards has the correct prefix for the properties `-ms-`, because in this way you will fix the problem. 

Regards,
Dragos

**Comment by dpedrinha** [comment]
Would you please give me an example?

Em qua, 15 de mai de 2019 04:11, dragosct <notifications@github.com>
escreveu:

**Comment by dragosct** [comment]
Hi! Sorry for the late response. I looked over the code and it seems that the prefixes for the CSS code are applied, so, unfortunately, we have to wait until the Microsoft edge will have another version with the proper support for the CSS props. 

Thank you for your understanding! 

Regards, 
Dragos

**Comment by dpedrinha** [comment]
Thank you for your reply.
If it's not asking too much, please report it to Microsoft because I'm not the only one going to have problems with it. I've done it already, but I'm sure you have a deeper knowledge to help them understand and fix the problem. I found it quite simple. On MS Edge, Options -> Help and Feedback -> Send Feedback.
Thanks

**Comment by dragosct** [comment]
Hi, @dpedrinha! Yes, we are sorry for this inconvenience and we already sent to Microsoft a message related to this issue and we hope that they will give us an answer quickly. 

Regards,
Dragos
