### ISSUE TITLE
Best practices to start a new project

### ISSUE THREAD

**Issue by dpedrinha** [creativetimofficial/ct-vue-material-kit-pro#9]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

When I first downloaded your code I unzipped everything, opened the project on VSCode and started creating my pages.
But right from the beginning I had to change a few things on your files. 
And I just came to realize that it will cause me problems in the future when I need to update your files.
So, I'd like to know the best practices, the best way to start a project in a way that when I have to update your files, I get the up-to-date code without overwriting the files I had to change.
I need to understand which files I can change and which I can not. And how should I deal with the changes I need without touching the core files. 

Thank you.

**Comment by dragosct** [comment]
Hi, @dpedrinha! Please, what things you had to change before starting your project? 

Regards, 
Dragos

**Comment by dpedrinha** [comment]
Well, for starters main.js, App.vue, router.js, index.html...
And let's say I want to change the default href color for the entire project, how would be the best way to do it and be able to install your updates without messing with my project?

**Comment by dpedrinha** [comment]
What about the plugins directory? Can I edit the files there? If not, how should I do?

**Comment by dragosct** [comment]
Hi! The easiest way to make updates is as follows:

* You create two repositories on a versioning control system (for example GitHub, GitLab, Bitbucket etc.)  - if it's a PRO paid product, we suggest that the repositories to be private
* On the first repository, you add our product unaltered
* On the second repository, you add our product and/or develop your project
* Each time we release a new version of the product at hand, you download again the product, and put it on top of the first repository, the versioning control system (for example GitHub, GitLab, Bitbucket etc.) will tell you all the differences between the versions
* By using a repository, you can even make new branches for each of our new version, that way, you will always have all the versions

Hope this information is of help. If you have further questions, let us know.

Regards,
Dragos
